xen-troops/meta-xt-prod-devel-rcar-gen4

README.md
=> README.md: Describe NFS boot configuration

meta-xt-domd-gen4/recipes-core/images/rcar-image-minimal.bbappend, meta-xt-domu-gen4/recipes-core/images/rcar-image-minimal.bbappend
=> domd/domu: add devmem utility to the images

meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/0001-Revert-arm64-dts-renesas-r8a779f0-spider-cpu-Enable-.patch, meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/0001-WIP-PCIe-MSI-support.patch, meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-domd.dts, meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas_%.bbappend
=> domd: Add initial support for PCIe/MSI/ITS on Spider

meta-xt-domx-gen4/recipes-extended/xen/xen-source.inc
=> xen: switch to spider-0.5.2 branch

meta-xt-domu-gen4/recipes-core/images/rcar-image-minimal.bbappend
=> domu: install NVME kernel modules

doc/tc-and-l3-offload.md
Signed-off-by: Dmytro Firsov <dmytro_firsov@epam.com>
=> doc: update L3 and TC offload docs for 0.8.7-release

doc/tc-and-l3-offload.md
Add instructions for VLAN routing offload testing.
Signed-off-by: Mykyta Poturai <mykyta_poturai@epam.com>
=> doc: update L3 and TC offload docs for 0.8.8-release

prod-devel-rcar-s4.yaml
Signed-off-by: Leonid Komarianskyi <leonid_komarianskyi@epam.com>
=> release: fix revision for kernel v5.10.41/rcar-5.1.7.rc6-xt

doc/tc-and-l3-offload.md
Updated documentation with description of testing procedure for multicast routing offload feature.
=> doc: add description for multicast routing offload feature

meta-xt-dom0-gen4/recipes-kernel/linux/linux-generic-armv8.bbappend, meta-xt-domd-gen4/recipes-bsp/arm-trusted-firmware/arm-trusted-firmware_git.bbappend, meta-xt-domd-gen4/recipes-bsp/u-boot/u-boot_2020.10.bbappend, meta-xt-domd-gen4/recipes-connectivity/snort/snort_%.bbappend, meta-xt-domd-gen4/recipes-core/base-files/base-files_%.bbappend, meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas_%.bbappend, meta-xt-domu-gen4/recipes-connectivity/vmq-network/vmq-network.bb, meta-xt-domu-gen4/recipes-kernel/linux/linux-renesas_%.bbappend, meta-xt-domx-gen4/recipes-bsp/optee-test/optee-test_git.bb, meta-xt-domx-gen4/recipes-bsp/optee/optee-os_git.bbappend, meta-xt-domx-gen4/recipes-extended/xen/xen-tools_git.bbappend, meta-xt-domx-gen4/recipes-extended/xen/xen_git.bbappend, meta-xt-domx-gen4/recipes-vendor/iccom-support/iccom-support.bb, meta-xt-driver-domain-gen4/recipes-connectivity/xen-network/xen-network.bbappend, meta-xt-driver-domain-gen4/recipes-core/images/rcar-image-minimal.bbappend, meta-xt-driver-domain-gen4/recipes-extended/xen/xen-tools_git.bbappend, meta-xt-driver-domain-gen4/recipes-extended/xen/xen_git.bbappend, meta-xt-prod-devel-rcar-control-gen4/recipes-extended/xen/xen-tools_git.bbappend, meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domd/domd.bbappend, meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domu/domu.bbappend, prod-devel-rcar-s4.yaml
- Replace override separator `_` with `:`
- yaml: replace `files` with `items`
=> Update override separators and image descriptor

meta-xt-domu-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-domu.dts
The patch is cherry-picked from spider-1.3.1 release brunch.
=> domu: add compatible string for PMU

doc/building.md
Minor fixes for documentation for master branch. The first patch is cherry-picked from spider-1.3.1 release brunch.
=> Minor fixes for documentation

prod-devel-rcar-s4.yaml
- introduce the MACHINE parameter;
- remove poky's default layers
=> Modifications to the yaml

meta-xt-dom0-gen4/recipes-kernel/linux/linux-generic-armv8.bbappend, meta-xt-domd-gen4/recipes-connectivity/daq/daq_2.0.6.bbappend, meta-xt-domd-gen4/recipes-connectivity/snort/snort_%.bbappend, meta-xt-driver-domain-gen4/recipes-connectivity/xen-network/xen-network.bbappend
- xen-network: fix override separator
- dom0: linux: use https to fetch from github
- daq: add the branch to URL 
- domd: snort: Fix misprint in FILES
=> Miscellaneous minor fixes

meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas_%.bbappend, meta-xt-domx-gen4/recipes-extended/xen/xen-source.inc
- override XEN_REV, so the product will be able to use its own revision on the required branch
- specify required URL, BRANCH and SRCREV for Linux kernel
=> Provide required revisions inside the product

layers/meta-xt-domx-gen4/recipes-security/optee/optee.inc
This PR is created just to merge the patch provided in the issue https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/issues/97
=> fix optee-os compatible for s4sk

prod-devel-rcar-s4.yaml
This commit adds changes required for the build of DomU.
=> yaml: updates for the DomU

layers/meta-xt-dom0-gen4/conf/layer.conf, layers/meta-xt-domd-gen4/conf/layer.conf, layers/meta-xt-domd-gen4/recipes-connectivity/snort/snort_%.bbappend, layers/meta-xt-domu-gen4/conf/layer.conf, layers/meta-xt-domx-gen4/conf/layer.conf, layers/meta-xt-domx-gen4/recipes-core/util-linux/util-linux_2.%.bbappend, layers/meta-xt-driver-domain-gen4/conf/layer.conf, layers/meta-xt-prod-devel-rcar-control-gen4/conf/layer.conf, prod-devel-rcar-s4.yaml
- snort: add packages for snort-tsn?
- yaml: add usrmerge to the DISTRO_FEATURES
- yaml: move systemd to the common configuration
- HACK: util-linux: remove libmount-mountfd-support
- domu: add meta-networking layer
- yaml: add .rootfs to all image names
- Upgrade to the yocto scarthgap
=> Upgrade to the yocto scarthgap

meta-xt-domd-gen4/recipes-core/images/rcar-image-minimal.bbappend, prod-devel-rcar4.yaml
Add overlays that switch to the new DDK source.
Enable GSX distro feature.
Add gles to rcar-image-minimal.
=> Enable GSX for V4H DomD

prod-devel-rcar4.yaml
Fixes: 544e164afa03 ("Enable GSX for V4H DomD")
=> yaml: Fix enabling of the GSX
