xen-troops/meta-xt-prod-devel-rcar-gen4

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-xen.dts
- meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domd/files/domd-spider.cfg
For the PCI to work:
- remove iommus bindings from pciec{0|1} as PCI host controller
is not doing any DMA operations
- add iommu-map and iommu-map-mask for pciec{0|1}
Suggested-by: Oleksandr Tyshchenko <oleksandr_tyshchenko@epam.com>
> xen.dts: update IPMMU settings

- meta-xt-domd-gen4/recipes-core/images/rcar-image-minimal.bbappend
They are needed to examine PCI devices during development.
> domd: install pciutils

- meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domd/files/domd-spider.cfg
There are two MMIO regions which are trapped and emulated by vPCI in Xen:
"dbi" and "config", so do not map these into DomD.
> domd: do not map vPCI MMIOs for pciec0

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-xen.dts
PCIe controller 0 may operate in two modes: Root Complex or
Endpoint. The are two corresponding device tree nodes for
that: pciec0 and pciec0_ep. So, when you want the controller
to be in a Root Complex mode then you put status = "disabled"
for the Endpoint entry and vise versa. Please note that both
nodes define the same "reg" and "interrupts" values.
Xen, when it initializes the trap handlers for PCI
configuration space access, needs the relevant regions to be
NOT mapped into Domain-0's address space, but because of the
current logic implemented it still assumes that the "disabled"
status is valid and maps. So, it doesn't map MMIOs for
the "okay" pciec0, but maps the same regions for pciec0_ep
which is "disabled". for that reason, remove pciec0_ep
node from the tree.
Signed-off-by: …
> domd: delete PCIEC0 Endpoint node

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/0001-HACK-spider-pci-do-not-look-at-PCI-link-up.patch
- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas_%.bbappend
While accessing child bus there is a check that PCI link is actually up
which currently (correctly) prevents the child bus from being scanned.
As we emulate PCI device at 0000:01:00.0 in Xen this doesn't allow the
emulation to run, so skip the check for now.
> [DO NOT MERGE] domd: [HACK] spider/pci: do not look at PCI link up

- prod-devel-rcar-s4.yaml
In this product yocto stores artifacts in generic-armv8-xt, not in
yocto-generic.
> yaml: fix path to dom0 kernel image

- prod-devel-rcar-s4.yaml
Move meta-renesas from fixed tag Renesas-Yocto-v5.8.2_S4 to dunfell
branch, this will allow us to track latest Renesas development,
including switch to rc8 kernel.
> yaml: switch meta-renesas to dunfell branch

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-xen.dts
As Xen has gained basic PCIE-IPMMU OSID support we can now update
bindings to describe which uTLB(s)/OSID(s) to use for particular
PCI device(s) represented by RID(BDF).
As it is not completely clear at the moment what devices we are going
to have and how to group (or separate) them describe the simple use-case
for now which can and will be adjusted later on.
As device and function bits are masked out all devices with bus
number 0 are mastered via uTLB corresponding to the OSID 0 and
all devices with bus number 1 via uTLB corresponding to the OSID 1.
Also restore "iommus" and remove "xen,force-assign-without-iommu"
property for the sake of removing the hack to allow assigning
platform side of host bridge without IOMMU, hopefully we have OSID
resources for doing that. But this of course …
> xen.dts: Update PCI IOMMU bindings according to the recent changes

- meta-xt-domd-gen4/recipes-core/base-files/base-files_%.bbappend
For some reason Renesas changes ownership of /var/volatile to nobody.
This scares systemd-tmpfiles, as it now sees symlink from root-owned
/var/log to nobody-owned /var/volatile/log and refuses to create
directories like /var/log/xen.
Revert this change so system can work properly.
> basefiles: don't change owner of /var/log to nobody

- meta-xt-driver-domain-gen4/recipes-connectivity/xen-network/xen-network.bbappend
This definition is added to xen-network.bb
-----
Need to be merged AFTER https://github.com/xen-troops/meta-xt-common/pull/20
> xen-network: Remove SYSTEMD_SERVICE_${PN} as duplicated

- doc/tc-and-l3-offload.md
This commit fixes typo in netns command and adds replay route for network namespace (or 2nd PC in 2 PC setup), that are needed to establish communication between testing host ports.
Signed-off-by: Dmytro Firsov <dmytro_firsov@epam.com>
Acked-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>
> doc: fix typo and add missing replay route

- meta-xt-dom0-gen4/conf/layer.conf
- meta-xt-domd-gen4/conf/layer.conf
- meta-xt-domu-gen4/conf/layer.conf
- meta-xt-domx-gen4/conf/layer.conf
- meta-xt-driver-domain-gen4/conf/layer.conf
- meta-xt-prod-devel-rcar-control-gen4/conf/layer.conf
To make sure that specific components can override/redefine settings from more generic levels, we set the following priorities for levels:
```
meta-xt-common     -  8
meta-xt-<platform> - 10
meta-xt-<product>  - 12
```
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>
> Set priority of layers to 12

- meta-xt-domd-gen4/recipes-bsp/u-boot/files/0001-net-rswtich-disable-GWCA-when-removing-driver.patch
- meta-xt-domd-gen4/recipes-bsp/u-boot/u-boot_2020.10.bbappend
Add patch that disables GWCA in rswitch_remove to avoid several issues that can be occurred after u-boot transfers control to Linux.
> domd: u-boot: fix rswitch GWCA issue

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-xen.dts
According to the commit d3218a4df ("arm64: dts: renesas: r8a779f0: spider-cpu: Reserve memory for Realtime core"), added by Phong Hoang to the renesas kernel [0], the last 512MB of the first memory bank is reserved for CR.
So we have to move ram address to bank2 so it will not overlap the existing memory and make reserved-region to forbid XEN from using this memory.
[0] https://github.com/renesas-rcar/linux-bsp.git
> Set memory bank to the free memory for rcar_spider

- prod-devel-rcar-s4.yaml
- yaml: use dunfell branch for meta-xt-common
- domd: Update version of linux
Have to be merged with https://github.com/xen-troops/meta-xt-prod-devel-rcar-gen4/pull/63
> Fix branch for xt-common and update DomD's Linux

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779f0-spider-xen.dts
Renesas kernel revision v5.10.41/rcar-5.1.7.rc11 contains updated device tree nodes, that break Xen hypervisor device tree build. Update them, according to Renesas changes.
> domd: update node names for v5.10.41/rcar-5.1.7.rc11 Xen device tree

- meta-xt-domu-gen4/recipes-kernel/linux/linux-renesas_%.bbappend
We have defconfig referenced twice for DomU's linux-renesas:
- KBUILD_DEFCONFIG
- SRC_URI
Ths results in two warnings during build time:
- `defconfig detected in WORKDIR. defconfig skipped`
- `defconfig was supplied both via KBUILD_DEFCONFIG and SRC_URI. Dropping SRC_URI defconfig`.
This commit removes not used defconfig from SRC_URI.
> domu: linux: Fix defconfig related warning

- meta-xt-domx-gen4/recipes-bsp/optee/files/0001-plat-rcar_gen4-extend-memory-available-to-OP-TEE.patch
- meta-xt-domx-gen4/recipes-bsp/optee/files/0002-arm-virtualization-don-t-allow-hypervisor-to-issue-s.patch
- meta-xt-domx-gen4/recipes-bsp/optee/optee-os_git.bbappend
This PR includes two patches:
- Fix memory layout so OP-TEE does not try to overwrite ARM-TF (aka BL31) memory
- Fix OP-TEE crash when baremetal kernel tries to communicate with it
> OP-TEE: Fix memory layout and fix baremetal crashes

- README.md
- doc/building.md
- Rename `Building` section to `Building and booting` in README.md.
- Do not separate boot instructions for Spider and S4SK boards.
- Replace `unset bootargs` with `env delete envargs`, because we do not have `unset` command in the u-boot.
> doc: Few minor fixes

- prod-devel-rcar-s4.yaml
Due to authors mistake invalid revisions were merged for meta-xt-common and meta-xt-rcaar.
This commit fixes that issue with proper revisions.
Fixes: 1e5a81a864b5 ("Upgrade to the yocto scarthgap")
> yaml: fix erroneous revisions

- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779g0-domd.dts
- meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas/r8a779g0-xen.dts
- meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domd/files/domd-whitehawk.cfg
- meta-xt-prod-devel-rcar-control-gen4/recipes-guests/domu/files/domu-whitehawk.cfg
This commit changes domd.dts, xen.dts, domd.cfg and domu.cfg so we have proper devices in domd to run camera.
Commit should be considered as the fixup, and be squashed into previous commits.
> dom0: domd: fixes required for the camera

- prod-devel-rcar4.yaml
All common data should be kept inside the build folder.
> yaml: move common_data inside the build directory

- layers/meta-xt-domd-gen4/recipes-extended/xen/xen_git.bbappend
We do not need to merge configs in the product, because this job is done in the `meta-virtualization` layer in the `xen-hypervisor.inc`.
---
See linked issue #122 for additional details.
> xen: remove the duplicated merge of configs

- layers/meta-xt-dom0-gen4/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
- layers/meta-xt-domd-gen4/recipes-kernel/inc/linux-sources.inc
- layers/meta-xt-domd-gen4/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
- layers/meta-xt-domd-gen4/recipes-kernel/linux/linux-renesas_%.bbappend
- layers/meta-xt-domu-gen4/recipes-kernel/inc/linux-sources.inc
- layers/meta-xt-domu-gen4/recipes-kernel/linux-libc-headers/linux-libc-headers_%.bbappend
- layers/meta-xt-domu-gen4/recipes-kernel/linux/linux-renesas_%.bbappend
- linux-libc-headers: fetch after linux only
- linux: use the same sources for libc headers
> Align sources for linux and linux-libc-headers, and fix the fetch race
